import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createState,tick,buy,netWorth,income,refresh,startJob,deliver,collect,ASSETS,STAGES,move,isBlocked,DURATION,assetSpot,SPAWN,BOARD,DROPS,PICKUPS} from '../src/model.js';
import data from '../src/map-data.js';
const playing=()=>{const s=createState();s.mode='playing';return s;};
test('starts at zero with no businesses',()=>{const s=createState();assert.equal(s.cash,0);assert.equal(netWorth(s),0);assert.equal(income(s),0);assert.deepEqual(s.owned,[]);});
test('cannot buy without funds or twice',()=>{const s=playing();assert.equal(buy(s,'coffee'),false);s.cash=16000;assert.equal(buy(s,'coffee'),true);assert.equal(buy(s,'coffee'),false);assert.equal(s.cash,0);});
test('purchase conserves capital',()=>{const s=playing();s.cash=100000;const before=netWorth(s);buy(s,'coffee');assert.equal(netWorth(s),before);assert.equal(s.cash,84000);});
test('income depends on active seconds',()=>{const a=playing(),b=playing();for(const s of[a,b]){s.cash=16000;buy(s,'coffee');}tick(a,10);for(let i=0;i<600;i++)tick(b,1/60);assert.ok(Math.abs(a.cash-b.cash)<.001);assert.equal(a.cash,7000);});
test('no income in menu pause results or invalid time',()=>{for(const mode of['menu','paused','results']){const s=playing();s.cash=16000;buy(s,'coffee');s.mode=mode;tick(s,10);assert.equal(s.cash,0);assert.equal(s.elapsed,0);}const s=playing();tick(s,-10);tick(s,NaN);assert.equal(s.elapsed,0);});
test('end cap pays only remaining active seconds',()=>{const s=playing();s.cash=16000;buy(s,'coffee');s.elapsed=299;tick(s,5);assert.equal(s.cash,700);assert.equal(s.elapsed,300);assert.equal(s.mode,'results');tick(s,100);assert.equal(s.cash,700);});
test('all outfits reachable and never downgrade',()=>{const s=playing();for(let i=0;i<STAGES.length;i++){s.cash=STAGES[i].at;refresh(s);assert.equal(s.stage,i);}s.cash=0;refresh(s);assert.equal(s.stage,4);});
test('two first deliveries fund a coffee shop',()=>{const s=playing();assert.ok(startJob(s));assert.equal(startJob(s),false);deliver(s);deliver(s);assert.ok(buy(s,'coffee'));assert.equal(income(s),700);});
test('pickup cooldown',()=>{const s=playing();assert.equal(collect(s,0),3000);assert.equal(collect(s,0),0);tick(s,24);assert.equal(collect(s,0),3000);assert.equal(collect(s,-1),0);});
test('actions rejected outside play',()=>{const s=createState();s.cash=1e8;assert.equal(buy(s,'coffee'),false);assert.equal(startJob(s),false);assert.equal(deliver(s),0);assert.equal(collect(s,0),0);});
const buildings=data.ways.filter(w=>w.tags.building).map(w=>({...w,minX:Math.min(...w.points.map(p=>p[0])),maxX:Math.max(...w.points.map(p=>p[0])),minZ:Math.min(...w.points.map(p=>p[1])),maxZ:Math.max(...w.points.map(p=>p[1]))}));
test('square boundary and central building collisions',()=>{assert.ok(isBlocked(0,0,buildings));assert.ok(isBlocked(-51,0,buildings));assert.ok(!isBlocked(SPAWN.x,SPAWN.z,buildings));const s=playing();s.player={x:-4,z:0};move(s,1,0,10,buildings,[]);assert.ok(s.player.x<-3);});
test('all destinations within accessible courtyard',()=>{for(const p of[SPAWN,BOARD,...DROPS,...PICKUPS,...ASSETS.map(assetSpot)])assert.equal(isBlocked(p.x,p.z,buildings),false,JSON.stringify(p));});
test('restart clears progress',()=>{const s=playing();s.cash=1e7;buy(s,'coffee');tick(s,250);const next=createState(s.hero);assert.equal(next.elapsed,0);assert.equal(next.cash,0);assert.deepEqual(next.owned,[]);});
test('model policy can reach the final stage in five minutes',()=>{const s=playing();startJob(s);for(let t=0;t<DURATION;t++){tick(s,1);if(t%10===9)deliver(s);for(const a of ASSETS)buy(s,a.id);}assert.equal(s.mode,'results');assert.ok(s.owned.length>=4);assert.equal(s.stage,4);});
