import { lighting, Picture } from './rendering.js';
import { loadMaterials } from './materials.js';
import { T } from './graphics.js';
import { Avatar, loadFaces } from './avatar.js';
import { createWorld, mapData } from './world.js';
import { DURATION,HEROES,STAGES,ASSETS,SPAWN,BOARD,DROPS,PICKUPS,assetSpot,createState,netWorth,income,tick,buy,refresh,startJob,deliver,collect,formatMoney,distance,move,pointInPolygon } from './model.js';
const $=id=>document.getElementById(id),mobile=()=>innerWidth<700,memory={};let storageWorks=true;
function read(key,fallback){try{const s=localStorage.getItem(key);return s?JSON.parse(s):fallback;}catch{storageWorks=false;return memory[key]??fallback;}}
function write(key,value){memory[key]=value;try{localStorage.setItem(key,JSON.stringify(value));}catch{storageWorks=false;}}
const saved=read('kante-v1-settings',{});let selected=Number.isInteger(saved.hero)&&saved.hero>=0&&saved.hero<4?saved.hero:2;
const names=HEROES.map((h,i)=>typeof saved.names?.[i]==='string'?saved.names[i].slice(0,20):h.name);
let quality=['low','medium','high'].includes(saved.quality)?saved.quality:'medium',sound=saved.sound===true;
const saveSettings=()=>write('kante-v1-settings',{hero:selected,names,quality,sound});
let state=createState(selected),shownStage=-1,lastFrame=0,uiClock=0,animationTime=0,handledEnd=false,cameraYaw=0,cameraPitch=.26,cameraDistance=5.2,moving=0,characterYaw=0,trackedAsset=null;
let picture;let toastTimer,bannerTimer,activeAction=null,modalReturn=null,audio=null,shareBlob=null,previousFocus=null,renderer,scene,camera,world,avatar,sunlight;
const keys=new Set(),joystick={x:0,y:0,id:null},target3=new T.Vector3(),cameraPos=new T.Vector3(),projected=new T.Vector3();
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400);}
function beep(kind='good'){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const o=audio.createOscillator(),gain=audio.createGain();o.connect(gain);gain.connect(audio.destination);const now=audio.currentTime;o.type='sine';o.frequency.setValueAtTime(kind==='level'?523:660,now);o.frequency.exponentialRampToValueAtTime(kind==='level'?1047:880,now+.14);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.035,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.24);o.start(now);o.stop(now+.25);}catch{}}
function resetInput(){keys.clear();joystick.x=joystick.y=0;joystick.id=null;$('stick').style.transform='';moving=0;}
function updateMode(){const gameView=state.mode==='playing'||state.mode==='paused';$('menu').hidden=state.mode!=='menu';$('hud').hidden=!gameView;$('results').hidden=state.mode!=='results';document.body.classList.toggle('playing',gameView);$('scene-caption').hidden=gameView;$('brand').hidden=gameView;}
function imageURL(id){return new URL(`../assets/head-${id}.webp`,import.meta.url).href;}
function selectHero(i){selected=i;state.hero=i;$('hero-name').value=names[i];$('hero-number').textContent=`0${i+1} / 04`;for(const[n,b]of Array.from($('hero-list').children).entries()){b.classList.toggle('selected',n===i);b.setAttribute('aria-pressed',String(n===i));}if(avatar)avatar.setLook(i,0);saveSettings();}
function begin(){closeModal();state=createState(selected);state.mode='playing';shownStage=-1;handledEnd=false;trackedAsset=null;cameraYaw=0;cameraPitch=.26;characterYaw=Math.PI;cameraDistance=5.2;resetInput();shareBlob=null;avatar.root.position.set(state.player.x,0,state.player.z);avatar.root.rotation.y=characterYaw;$('control-hint').style.opacity='1';$('level-banner').hidden=true;$('hud-face').src=imageURL(HEROES[selected].id);applyProgress(true);updateMode();updateUI();beep();if(!storageWorks)toast('Рекорды сохраняются только до закрытия этой вкладки');}
function showMenu(){closeModal();state=createState(selected);shownStage=-1;resetInput();trackedAsset=null;avatar.root.position.set(SPAWN.x,0,SPAWN.z);avatar.setLook(selected,0);world.kiosks.forEach(k=>k.upgrades.visible=false);world.premiumCar.visible=false;world.ring.visible=world.beam.visible=false;world.pickups.forEach(p=>p.visible=false);updateMode();}
function pause(){if(state.mode!=='playing')return;state.mode='paused';resetInput();openPause();}
function resume(){if(state.mode==='paused')state.mode='playing';resetInput();lastFrame=performance.now();closeModal(false);updateMode();}
function openModal(title,build){previousFocus=document.activeElement;if(state.mode==='playing'){state.mode='paused';modalReturn='playing';resetInput();}else modalReturn=null;const content=$('modal-content');content.replaceChildren();const h=document.createElement('h2');h.textContent=title;content.append(h);build(content);$('modal-layer').hidden=false;$('modal-close').focus();}
function closeModal(restore=true){$('modal-layer').hidden=true;if(restore&&modalReturn==='playing'&&state.mode==='paused')state.mode='playing';modalReturn=null;resetInput();lastFrame=performance.now();if(previousFocus instanceof HTMLElement)previousFocus.focus({preventScroll:true});}
function button(parent,text,fn,cls='secondary'){const b=document.createElement('button');b.className=cls;b.textContent=text;b.addEventListener('click',fn);parent.append(b);return b;}
function paragraph(parent,text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;parent.append(p);return p;}
function openPause(){openModal('На паузе',c=>{paragraph(c,'Время остановлено. Доход тоже отдыхает.');button(c,'Продолжить',resume,'primary');const row=document.createElement('div');row.className='setting-row';row.append(document.createTextNode('Звук'));button(row,sound?'Включён':'Выключен',()=>{sound=!sound;saveSettings();row.querySelector('button').textContent=sound?'Включён':'Выключен';beep();});c.append(row);const row2=document.createElement('div');row2.className='setting-row';row2.append(document.createTextNode('Графика'));button(row2,{low:'Легче',medium:'Баланс',high:'Выше'}[quality],()=>{quality={low:'medium',medium:'high',high:'low'}[quality];applyQuality();saveSettings();row2.querySelector('button').textContent={low:'Легче',medium:'Баланс',high:'Выше'}[quality];});c.append(row2);paragraph(c,'Телефон: левый круг — идти, правая часть экрана — вращать камеру. Компьютер: WASD / стрелки, E — действие, мышь — камера.','muted');button(c,'Начать заново',begin);button(c,'Выйти к выбору героя',showMenu,'text-btn');});modalReturn='playing';}
function about(){openModal('Ваш двор в 3D',c=>{paragraph(c,'Версия 1.2: детализированный двор, отдельные интерьеры бизнесов, объёмная одежда и живое освещение. Игровой квадрат 100 × 100 метров с центром 55.633587, 37.654592. По данным OpenStreetMap точка находится в доме: Пролетарский проспект, 18 к3. Вход в метро в квадрат не попадает.');paragraph(c,'Контуры домов, этажность, подъезды и дорожки взяты из OpenStreetMap. Фасады, деревья, машины и коммерческие павильоны — художественная интерпретация. Бизнесы вымышленные; реальные организации к игре не относятся.');paragraph(c,'Герои — объёмные модели с анимацией и фотографическими текстурами лиц. Это не 3D-сканирование: профиль и тело приблизительные.');paragraph(c,'Возьми заказ у стенда, доставляй посылки, собирай золотые конверты и покупай бизнесы. Доход начисляется только во время игры. Одежда и атрибуты меняются с ростом капитала.');paragraph(c,'Экономика намеренно ускорена, это не прогноз доходности. Нет платежей, аналитики, регистрации или общей таблицы. Имена и рекорды остаются в браузере.','muted');button(c,'Понятно',()=>closeModal(),'primary');});}
function records(){openModal('Рекорды на этом устройстве',c=>{const rows=read('kante-v1-records',[]);if(!Array.isArray(rows)||!rows.length)paragraph(c,'Первое место пока свободно.');else rows.slice(0,10).forEach((r,i)=>{const row=document.createElement('div');row.className='record-row';const name=document.createElement('span');name.textContent=`${i+1}. ${String(r.name||'Партнёр').slice(0,20)}`;const val=document.createElement('b');val.textContent=formatMoney(Number(r.worth)||0);row.append(name,val);c.append(row);});paragraph(c,'Это локальные результаты, не общая таблица друзей.','muted');});}
function portfolio(){openModal('Свои активы',c=>{paragraph(c,'Покупай на месте. После покупки бизнес приносит доход сам — пока идёт игровое время.');for(const a of ASSETS){const owned=state.owned.includes(a.id),row=document.createElement('div');row.className='biz';const n=document.createElement('span');n.className='num';n.textContent=a.no;const d=document.createElement('div'),title=document.createElement('b'),desc=document.createElement('small');title.textContent=a.name;desc.textContent=(owned?'Твой актив':formatMoney(a.price))+' · +'+formatMoney(a.income)+'/с';d.append(title,desc);row.append(n,d);button(row,owned?'К активу':'На карте',()=>{trackedAsset=a.id;closeModal();updateUI();});c.append(row);}paragraph(c,'Капитал = наличные + стоимость купленных бизнесов. Покупка не создаёт деньги из воздуха.','muted');});}
function goal(){if(trackedAsset){const a=ASSETS.find(a=>a.id===trackedAsset);if(a&&!state.owned.includes(a.id))return{...assetSpot(a),name:a.name,type:'asset',asset:a};trackedAsset=null;}if(state.job)return{...DROPS[state.job.index],name:'Доставка',type:'delivery'};return{...BOARD,name:'Первые заказы',type:'board'};}
function updateAction(){activeAction=null;const nearby=ASSETS.map(a=>({a,d:distance(state.player,assetSpot(a))})).filter(x=>x.d<3&&!state.owned.includes(x.a.id)).sort((a,b)=>a.d-b.d)[0];if(nearby){const a=nearby.a;activeAction={type:'buy',a};$('action-text').textContent=state.cash>=a.price?`Купить: ${formatMoney(a.price)}`:`Ещё ${formatMoney(a.price-state.cash)} до покупки`;$('interact').disabled=state.cash<a.price;return;}if(!state.job&&distance(state.player,BOARD)<3){activeAction={type:'job'};$('action-text').textContent='Взять первый заказ';}else if(state.job&&distance(state.player,DROPS[state.job.index])<2.5){activeAction={type:'deliver'};$('action-text').textContent=`Сдать: +${formatMoney(state.job.reward)}`;}else $('action-text').textContent='Подойди к маркеру';$('interact').disabled=!activeAction;}
function interact(){if(state.mode!=='playing')return;updateAction();if(!activeAction)return;if(activeAction.type==='buy'){const a=activeAction.a;if(buy(state,a.id)){world.effects.burst(state.player.x,state.player.z,true);toast(a.name+' теперь твоя. +'+formatMoney(a.income)+'/с');trackedAsset=null;beep('level');}}else if(activeAction.type==='job'){startJob(state);toast('Первый заказ взят. Найди золотой маркер.');beep();}else{const pay=deliver(state);world.effects.burst(state.player.x,state.player.z);toast('Заказ выполнен. +'+formatMoney(pay));beep();}applyProgress();updateUI();}
function applyProgress(silent=false){world.kiosks.forEach((k,i)=>{k.upgrades.visible=state.owned.includes(ASSETS[i].id);});world.premiumCar.visible=state.stage>=4;if(shownStage!==state.stage){const previous=shownStage;shownStage=state.stage;avatar.setLook(state.hero,state.stage);if(!silent&&previous>=0&&shownStage>previous){world.effects.burst(state.player.x,state.player.z,true);$('level-title').textContent=STAGES[state.stage].title;$('level-clothes').textContent=STAGES[state.stage].clothes;$('level-banner').hidden=false;clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('level-banner').hidden=true,3000);beep('level');}}}
function updateUI(){$('cash').textContent=formatMoney(state.cash);$('rate').textContent='+'+formatMoney(income(state))+'/с';const remaining=Math.max(0,Math.ceil(DURATION-state.elapsed));$('timer').textContent=`${Math.floor(remaining/60).toString().padStart(2,'0')}:${(remaining%60).toString().padStart(2,'0')}`;$('timer').classList.toggle('urgent',remaining<=30);$('worth').textContent='Капитал: '+formatMoney(netWorth(state));$('status-name').textContent=STAGES[state.stage].title;$('level-number').textContent='0'+(state.stage+1);$('owned-count').textContent=state.owned.length+' / 5';const next=STAGES[state.stage+1]?.at;$('progress-fill').style.width=(next?Math.min(1,(state.peak-STAGES[state.stage].at)/(next-STAGES[state.stage].at))*100:100)+'%';const g=goal();$('mission-kicker').textContent=g.type==='asset'?'СЛЕДУЮЩИЙ АКТИВ':state.job?'ЗАКАЗ ПО РАЙОНУ':'ПЕРВЫЙ КАПИТАЛ';$('mission-title').textContent=g.type==='asset'?g.name:state.job?'Доставь заказ: +'+formatMoney(state.job.reward):'Возьми заказ у стенда';$('mission-note').textContent=g.type==='asset'?formatMoney(g.asset.price)+' · +'+formatMoney(g.asset.income)+'/с':Math.round(distance(state.player,g))+' м до цели · E / кнопка справа';updateAction();drawMinimap();}
function drawMinimap(){const c=$('minimap').getContext('2d'),scale=1.94,p=(x,z)=>[110+x*scale,110+z*scale];c.clearRect(0,0,220,220);c.fillStyle='#d9e0cc';c.fillRect(6,6,208,208);c.save();c.beginPath();c.rect(6,6,208,208);c.clip();for(const w of mapData.ways){if(w.tags.building){c.fillStyle='#9daa98';c.beginPath();w.points.forEach(([x,z],i)=>{const[px,py]=p(x,z);i?c.lineTo(px,py):c.moveTo(px,py);});c.closePath();c.fill();}else if(w.tags.highway){c.strokeStyle=w.tags.highway==='service'?'#c0c8b6':'#b9c3b1';c.lineWidth=w.tags.highway==='service'?7:2;c.beginPath();w.points.forEach(([x,z],i)=>{const[px,py]=p(x,z);i?c.lineTo(px,py):c.moveTo(px,py);});c.stroke();}}ASSETS.forEach(a=>{const[x,y]=p(a.x,a.z);c.fillStyle=state.owned.includes(a.id)?'#3c7350':'#d2af66';c.fillRect(x-4,y-4,8,8);});const g=goal(),gp=p(g.x,g.z),pp=p(state.player.x,state.player.z);c.strokeStyle='#be9b53';c.lineWidth=1.6;c.setLineDash([4,4]);c.beginPath();c.moveTo(...pp);c.lineTo(...gp);c.stroke();c.setLineDash([]);c.strokeStyle='#c7a760';c.lineWidth=2;c.beginPath();c.arc(...gp,6,0,Math.PI*2);c.stroke();c.save();c.translate(...pp);c.rotate(-characterYaw);c.beginPath();c.moveTo(0,7);c.lineTo(-4.5,-4);c.lineTo(4.5,-4);c.closePath();c.fillStyle='#244a3a';c.fill();c.strokeStyle='#fff3d8';c.lineWidth=1.5;c.stroke();c.restore();c.restore();}
function worldUpdates(t){const game=state.mode==='playing'||state.mode==='paused';world.ring.visible=world.beam.visible=game;if(game){const g=goal();world.ring.position.set(g.x,.08,g.z);world.ring.scale.setScalar(1+Math.sin(t*3)*.055);world.beam.position.set(g.x,1.1,g.z);projected.set(g.x,2.9,g.z).project(camera);const visible=projected.z>-1&&projected.z<1&&Math.abs(projected.x)<.91&&Math.abs(projected.y)<.75;$('target-label').hidden=!visible;if(visible){$('target-label').style.left=(projected.x*.5+.5)*innerWidth+'px';$('target-label').style.top=(-projected.y*.5+.5)*innerHeight+'px';$('target-name').textContent=g.name;$('target-distance').textContent=Math.round(distance(state.player,g))+' м';}}for(let i=0;i<world.pickups.length;i++){const p=world.pickups[i];p.visible=game&&state.elapsed-state.collected[i]>=24;p.rotation.y=t*.8+i;p.position.y=.72+Math.sin(t*2.2+i)*.12;if(p.visible&&state.mode==='playing'&&distance(state.player,PICKUPS[i])<1.2){const pay=collect(state,i);if(pay){world.effects.burst(state.player.x,state.player.z);toast('Оплата заказа: +'+formatMoney(pay));beep();}}}}
function updateCamera(dt){if(state.mode==='menu'||state.mode==='results'){const pos=avatar.root.position,small=mobile();target3.set(pos.x,small?1.0:1.08,pos.z);cameraPos.set(pos.x+(small?1.1:1.35),small?2.2:1.82,pos.z+(small?5.5:3.4));camera.position.lerp(cameraPos,Math.min(1,dt*5));camera.lookAt(target3);camera.fov=44;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camera.projectionMatrix.elements[8]=small?0:.39;const panel=(state.mode==='menu'?$('menu'):$('results')).getBoundingClientRect();const focus=Math.max(190,(86+panel.top-12)/2);camera.projectionMatrix.elements[9]=small?2*(focus/innerHeight-.5):0;camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();return;}target3.set(state.player.x,1.08,state.player.z);const d=mobile()?cameraDistance:cameraDistance*.9;cameraPos.set(target3.x+Math.sin(cameraYaw)*d,target3.y+d*cameraPitch,target3.z+Math.cos(cameraYaw)*d);const delta=cameraPos.clone().sub(target3),len=delta.length();for(let dist=.8;dist<len;dist+=.35){const p=target3.clone().addScaledVector(delta,dist/len),blocked=world.buildings.some(b=>p.x>b.minX-.25&&p.x<b.maxX+.25&&p.z>b.minZ-.25&&p.z<b.maxZ+.25&&pointInPolygon(p.x,p.z,b.points));if(blocked){cameraPos.copy(target3).addScaledVector(delta,Math.max(.8,dist-.65)/len);break;}}camera.position.lerp(cameraPos,Math.min(1,dt*9));camera.lookAt(target3);camera.fov=53;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
function frame(ts){requestAnimationFrame(frame);const dt=Math.min(.1,Math.max(0,(ts-(lastFrame||ts))/1000));lastFrame=ts;if(!renderer||document.hidden)return;const active=state.mode==='playing';if(active){let mx=joystick.x,my=joystick.y;if(keys.has('a')||keys.has('arrowleft'))mx-=1;if(keys.has('d')||keys.has('arrowright'))mx+=1;if(keys.has('w')||keys.has('arrowup'))my+=1;if(keys.has('s')||keys.has('arrowdown'))my-=1;const vx=mx*Math.cos(cameraYaw)-my*Math.sin(cameraYaw),vz=-mx*Math.sin(cameraYaw)-my*Math.cos(cameraYaw),old={...state.player};move(state,vx,vz,dt,world.buildings,world.obstacles);const actual=distance(old,state.player);moving=actual>.0005?Math.min(1,Math.hypot(mx,my)):0;if(moving)characterYaw=Math.atan2(vx,vz);tick(state,dt);animationTime+=dt;avatar.root.position.set(state.player.x,0,state.player.z);avatar.update(animationTime,moving,characterYaw);applyProgress();if(state.elapsed>13)$('control-hint').style.opacity='0';}else if(state.mode==='menu'||state.mode==='results'){animationTime+=dt;avatar.update(animationTime,0,.43);}updateCamera(dt);worldUpdates(animationTime);world.leaves.userData.wind.time.value=matchMedia('(prefers-reduced-motion: reduce)').matches?0:animationTime;world.effects.update(state.mode==='paused'?0:dt);const sx=Math.round(avatar.root.position.x/2)*2,sz=Math.round(avatar.root.position.z/2)*2;sunlight.target.position.set(sx,0,sz);sunlight.position.set(sx-27,36,sz+23);uiClock+=dt;if(uiClock>.12&&(active||state.mode==='paused')){updateUI();uiClock=0;}if(state.mode==='results'&&!handledEnd)endGame();picture.render();}
function applyQuality(){
 const ratio={low:.85,medium:mobile()?1.15:1.35,high:1.6}[quality];
 renderer.setPixelRatio(Math.min(devicePixelRatio||1,ratio));
 renderer.setSize(innerWidth,innerHeight,false);
 renderer.shadowMap.enabled=quality!=='low';
 const size=quality==='high'?2048:1536;
 if(sunlight.shadow.mapSize.x!==size){
  sunlight.shadow.mapSize.set(size,size);
  if(sunlight.shadow.map){sunlight.shadow.map.dispose();sunlight.shadow.map=null;}
 }
 picture?.resize(quality);
}
function endGame(){handledEnd=true;resetInput();clearTimeout(bannerTimer);$('level-banner').hidden=true;world.ring.visible=world.beam.visible=false;world.pickups.forEach(p=>p.visible=false);const value=netWorth(state);$('result-face').src=imageURL(HEROES[state.hero].id);$('result-name').textContent=names[state.hero];$('result-status').textContent=STAGES[state.stage].title;$('result-worth').textContent=formatMoney(value,true);$('result-assets').textContent=state.owned.length+' / 5';$('result-income').textContent=formatMoney(income(state));$('result-jobs').textContent=state.deliveries;let rows=read('kante-v1-records',[]);if(!Array.isArray(rows))rows=[];rows=rows.filter(r=>Number.isFinite(r.worth));const prev=rows.filter(r=>r.hero===state.hero).reduce((n,r)=>Math.max(n,r.worth),0);rows.push({hero:state.hero,name:names[state.hero],worth:value,stage:state.stage,date:Date.now()});rows.sort((a,b)=>b.worth-a.worth);write('kante-v1-records',rows.slice(0,10));$('personal-best').textContent=value>prev?'Новый личный рекорд на этом устройстве.':'Личный рекорд: '+formatMoney(prev,true);updateMode();}
async function createShareCard(){const c=document.createElement('canvas');c.width=900;c.height=1120;const ctx=c.getContext('2d');ctx.fillStyle='#e9ecdc';ctx.fillRect(0,0,900,1120);ctx.fillStyle='#234b3b';ctx.fillRect(0,0,900,335);ctx.fillStyle='#e7ce91';ctx.font='bold 21px Arial';ctx.fillText('ПАЦАНЫ В АКТИВЕ / КАНТЕМИРОВСКАЯ 3D',60,70);ctx.fillStyle='#f4edda';ctx.font='56px Georgia';ctx.fillText('Начинал с нуля.',60,157);ctx.fillText('Нулей стало больше.',60,225);const img=new Image();img.src=imageURL(HEROES[state.hero].id);await img.decode();ctx.fillStyle='#d0ddc6';ctx.fillRect(60,385,190,215);const ratio=Math.min(180/img.width,205/img.height);ctx.drawImage(img,155-img.width*ratio/2,594-img.height*ratio,img.width*ratio,img.height*ratio);ctx.fillStyle='#294b3a';ctx.font='bold 33px Arial';ctx.fillText(names[state.hero],285,455,550);ctx.font='26px Arial';ctx.fillText(STAGES[state.stage].title,285,502);ctx.fillStyle='#6a7f66';ctx.font='22px Arial';ctx.fillText('0 ₽ → '+formatMoney(netWorth(state),true),285,549,550);ctx.fillStyle='#72846b';ctx.font='19px Arial';ctx.fillText('КАПИТАЛ ЗА ПЯТЬ МИНУТ',60,675);ctx.fillStyle='#284d38';ctx.font='bold 70px Arial';ctx.fillText(formatMoney(netWorth(state),true),60,771,780);ctx.font='25px Arial';ctx.fillText(state.owned.length+' / 5 бизнесов',60,850);ctx.fillText('+'+formatMoney(income(state))+'/с',470,850);ctx.strokeStyle='#b8c6aa';ctx.beginPath();ctx.moveTo(60,910);ctx.lineTo(840,910);ctx.stroke();ctx.fillStyle='#667e5d';ctx.font='22px Arial';ctx.fillText('Твой ход. Собери больше.',60,972);ctx.font='17px Arial';ctx.fillText('Игровая экономика. Результат на этом устройстве.',60,1040);shareBlob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));return c;}
async function shareResult(){const link=new URL(location.href);link.search='';link.hash='';const text=`${names[state.hero]}: ${formatMoney(netWorth(state),true)} за 5 минут. Пацаны в активе — Кантемировская 3D. Твой ход: ${link.href}`;if(!shareBlob)await createShareCard();const file=shareBlob?new File([shareBlob],'moy-kapital.png',{type:'image/png'}):null;if(file&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],text,title:'Пацаны в активе'});return;}catch(e){if(e.name==='AbortError')return;}}openModal('Отправь свой результат',c=>{const objectURL=shareBlob?URL.createObjectURL(shareBlob):null;if(objectURL){const img=document.createElement('img');img.src=objectURL;img.className='share-img';img.alt='Карточка результата';c.append(img);const a=document.createElement('a');a.className='secondary download-btn';a.href=objectURL;a.download='moy-kapital.png';a.textContent='Сохранить картинку';c.append(a);setTimeout(()=>URL.revokeObjectURL(objectURL),180000);}const area=document.createElement('textarea');area.className='share-text';area.value=text;area.readOnly=true;area.setAttribute('aria-label','Текст и ссылка для отправки');c.append(area);button(c,'Скопировать текст и ссылку',async()=>{try{await navigator.clipboard.writeText(text);}catch{area.focus();area.select();}},'primary');if(location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.protocol==='file:')paragraph(c,'Сейчас открыт локальный файл. Для друзей нужна публикация сайта; localhost с их телефонов не откроется.','muted');});}
function controls(){
 $('start').onclick=begin;$('restart').onclick=begin;$('to-menu').onclick=showMenu;$('pause').onclick=pause;$('interact').onclick=interact;$('portfolio-button').onclick=portfolio;$('camera').onclick=()=>{cameraYaw+=Math.PI;};$('about-button').onclick=about;$('records-button').onclick=records;$('share').onclick=shareResult;$('modal-close').onclick=()=>{if(state.mode==='paused')resume();else closeModal();};$('hero-name').oninput=e=>{names[selected]=e.target.value.slice(0,20);saveSettings();};$('hero-name').onblur=()=>{if(!names[selected].trim()){names[selected]=HEROES[selected].name;$('hero-name').value=names[selected];saveSettings();}};
 const joy=$('joystick');function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.31,len=Math.hypot(dx,dy),k=len>max?max/len:1;joystick.x=dx*k/max;joystick.y=-dy*k/max;$('stick').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
 joy.addEventListener('pointerdown',e=>{if(state.mode!=='playing'||joystick.id!==null)return;e.preventDefault();joystick.id=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===joystick.id)joyMove(e);});const up=e=>{if(e.pointerId===joystick.id)resetInput();};joy.addEventListener('pointerup',up);joy.addEventListener('pointercancel',up);joy.addEventListener('lostpointercapture',up);
 let drag=null;$('world').addEventListener('pointerdown',e=>{if(state.mode!=='playing')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id||state.mode!=='playing')return;cameraYaw-=(e.clientX-drag.x)*.006;cameraPitch=Math.max(.06,Math.min(.80,cameraPitch+(e.clientY-drag.y)*.003));drag.x=e.clientX;drag.y=e.clientY;});for(const ev of['pointerup','pointercancel','lostpointercapture'])$('world').addEventListener(ev,()=>{drag=null;});$('world').addEventListener('wheel',e=>{if(state.mode!=='playing')return;e.preventDefault();cameraDistance=Math.max(3.8,Math.min(13,cameraDistance+e.deltaY*.009));},{passive:false});
 addEventListener('keydown',e=>{if(!$('modal-layer').hidden&&e.key==='Tab'){const f=[...$('modal').querySelectorAll('button,a[href],textarea,input')].filter(n=>!n.disabled),first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;const k=e.key.toLowerCase();if((k==='escape'||k==='p')&&!e.repeat){if(!$('modal-layer').hidden)$('modal-close').click();else if(state.mode==='playing')pause();return;}if(state.mode!=='playing')return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){e.preventDefault();keys.add(k);}if((k==='e'||k===' ')&&!e.repeat)interact();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{resetInput();if(state.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();lastFrame=performance.now();});addEventListener('resize',()=>{if(renderer)applyQuality();});
}
async function init(){try{
 renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance',alpha:false});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();
 camera=new T.PerspectiveCamera(53,innerWidth/innerHeight,.07,180);
 sunlight=await lighting(renderer,scene);
 picture=new Picture(renderer,scene,camera);
 await loadMaterials();
 world=createWorld(scene);await loadFaces();avatar=new Avatar(scene,selected,0);avatar.root.position.set(SPAWN.x,0,SPAWN.z);avatar.root.rotation.y=.43;camera.position.set(SPAWN.x+2,2.2,SPAWN.z+4.5);for(let i=0;i<HEROES.length;i++){const b=document.createElement('button');b.className='hero-option';b.setAttribute('aria-label',HEROES[i].subtitle);b.setAttribute('aria-pressed','false');const img=document.createElement('img');img.src=imageURL(HEROES[i].id);img.alt=HEROES[i].subtitle;b.append(img);b.onclick=()=>selectHero(i);$('hero-list').append(b);}controls();selectHero(selected);applyQuality();showMenu();$('loading').style.opacity='0';setTimeout(()=>$('loading').hidden=true,550);requestAnimationFrame(frame);
 $('world').addEventListener('webglcontextlost',e=>{e.preventDefault();if(state.mode==='playing')pause();openModal('Графика временно остановлена',c=>{paragraph(c,'Браузер освободил графическую память. Перезагрузи страницу и выбери более лёгкую графику в паузе. Текущий забег не сохранится.');button(c,'Перезагрузить',()=>location.reload(),'primary');});});
 if((location.hostname==='127.0.0.1'||location.hostname==='localhost')&&new URLSearchParams(location.search).get('test')==='1'){window.__test={state:()=>structuredClone(state),stats:()=>({calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures}),advance:dt=>{tick(state,dt);applyProgress(true);updateUI();if(state.mode==='results'&&!handledEnd)endGame();},warp:(x,z)=>{state.player.x=x;state.player.z=z;avatar.root.position.set(x,0,z);updateUI();},funds:v=>{state.cash=v;refresh(state);applyProgress(true);updateUI();},look:(hero,stage)=>avatar.setLook(hero,stage),camera:(yaw,pitch=.26,dist=5.2)=>{cameraYaw=yaw;cameraPitch=pitch;cameraDistance=dist;},quality:v=>{quality=v;applyQuality();},pause,resume,begin,buy:id=>{const result=buy(state,id);applyProgress(true);updateUI();return result;}};}
 }catch(error){console.error(error);$('loading').replaceChildren();const p=document.createElement('p');p.textContent='Не удалось запустить 3D';$('loading').append(p);const small=document.createElement('small');small.style.cssText='max-width:300px;text-align:center;line-height:1.7;letter-spacing:0';small.textContent='Нужен браузер с WebGL 2. Обнови страницу в Safari или Chrome. Если ресурсы не загрузились, проверь подключение. '+error.message;$('loading').append(small);button($('loading'),'Попробовать снова',()=>location.reload());}}
init();
