export const VERSION='1.0.0',DURATION=300,SPAWN={x:-22,z:37};
export const HEROES=[{id:'left',name:'Партнёр 1',subtitle:'Слева на фото',skin:'#ceaa91',hair:'#625d53'},{id:'back',name:'Партнёр 2',subtitle:'Сзади на фото',skin:'#d3a286',hair:'#332a25'},{id:'center',name:'Партнёр 3',subtitle:'В центре фото',skin:'#cda38a',hair:'#686458'},{id:'right',name:'Партнёр 4',subtitle:'Справа на фото',skin:'#d5ad95',hair:'#44372f'}];
export const STAGES=[{at:0,title:'С нуля',clothes:'Худи и старые кроссовки'},{at:30000,title:'Первые деньги',clothes:'Новая куртка и часы'},{at:150000,title:'Предприниматель',clothes:'Рубашка и смартфон'},{at:600000,title:'Владелец бизнеса',clothes:'Костюм и портфель'},{at:2500000,title:'Владелец капитала',clothes:'Премиальный костюм и автомобиль'}];
export const ASSETS=[{id:'coffee',name:'Кофейня',label:'КОФЕ / 18',price:16000,income:700,x:-11,z:28,color:'#bf8250',no:'01'},{id:'shop',name:'Онлайн-магазин',label:'ТОЧКА ВЫДАЧИ',price:80000,income:3000,x:-33,z:10,color:'#538f91',no:'02'},{id:'cargo',name:'Логистика',label:'СВОЯ ЛОГИСТИКА',price:280000,income:10000,x:-11,z:-7,color:'#607eaf',no:'03'},{id:'ai',name:'AI-студия',label:'РАЗУМ / AI',price:900000,income:32000,x:-33,z:-25,color:'#8573ad',no:'04'},{id:'holding',name:'Управляющая компания',label:'СВОЙ КАПИТАЛ',price:2400000,income:90000,x:-11,z:-42,color:'#bca36a',no:'05'}];
export const BOARD={x:-28,z:35};
export const DROPS=[{x:-13,z:17},{x:-32,z:-2},{x:-12,z:-20},{x:-32,z:-38},{x:-13,z:40},{x:-30,z:25}];
export const PICKUPS=[{x:-18,z:22},{x:-27,z:6},{x:-17,z:-12},{x:-28,z:-30},{x:-18,z:-41},{x:-28,z:43}];
export function assetSpot(a){return{x:a.x+(a.x<-22?3.4:-3.4),z:a.z};}
export function createState(hero=2){return{mode:'menu',hero,cash:0,owned:[],elapsed:0,peak:0,stage:0,deliveries:0,job:null,collected:PICKUPS.map(()=>-100),player:{...SPAWN},ended:false};}
export function netWorth(s){return s.cash+s.owned.reduce((n,id)=>n+ASSETS.find(a=>a.id===id).price,0);}
export function income(s){return s.owned.reduce((n,id)=>n+ASSETS.find(a=>a.id===id).income,0);}
export function refresh(s){s.peak=Math.max(s.peak,netWorth(s));s.stage=STAGES.reduce((n,a,i)=>s.peak>=a.at?i:n,0);}
export function tick(s,dt){if(s.mode!=='playing'||!Number.isFinite(dt)||dt<=0)return;const active=Math.min(dt,Math.max(0,DURATION-s.elapsed));s.cash+=income(s)*active;s.elapsed+=active;refresh(s);if(s.elapsed>=DURATION){s.mode='results';s.ended=true;}}
export function buy(s,id){const a=ASSETS.find(a=>a.id===id);if(s.mode!=='playing'||!a||s.owned.includes(id)||s.cash+1e-6<a.price)return false;s.cash=Math.max(0,s.cash-a.price);s.owned.push(id);refresh(s);return true;}
export function startJob(s){if(s.mode!=='playing'||s.job)return false;s.job={index:s.deliveries%DROPS.length,reward:8000*(1+s.stage*1.3)};return true;}
export function deliver(s){if(s.mode!=='playing'||!s.job)return 0;const pay=s.job.reward;s.cash+=pay;s.deliveries++;s.job=null;refresh(s);startJob(s);return pay;}
export function collect(s,index){if(s.mode!=='playing'||index<0||index>=PICKUPS.length||s.elapsed-s.collected[index]<24)return 0;const pay=3000*(1+s.stage);s.cash+=pay;s.collected[index]=s.elapsed;refresh(s);return pay;}
export function formatMoney(v,full=false){if(full)return Math.floor(v).toLocaleString('ru-RU')+' ₽';return v>=1e6?(v/1e6).toLocaleString('ru-RU',{maximumFractionDigits:2})+' млн ₽':v>=1000?(v/1000).toLocaleString('ru-RU',{maximumFractionDigits:1})+' тыс. ₽':Math.floor(v)+' ₽';}
export function distance(a,b){return Math.hypot(a.x-b.x,a.z-b.z);}
export function pointInPolygon(x,z,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const[xi,zi]=points[i],[xj,zj]=points[j];if((zi>z)!==(zj>z)&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)inside=!inside;}return inside;}
export function isBlocked(x,z,buildings,obstacles=[],radius=.36){if(Math.abs(x)>49.45||Math.abs(z)>49.45)return true;for(const b of buildings){if(x<b.minX-radius||x>b.maxX+radius||z<b.minZ-radius||z>b.maxZ+radius)continue;for(const[dx,dz]of[[0,0],[radius,0],[-radius,0],[0,radius],[0,-radius]])if(pointInPolygon(x+dx,z+dz,b.points))return true;}return obstacles.some(b=>x>b.x-b.w/2-radius&&x<b.x+b.w/2+radius&&z>b.z-b.d/2-radius&&z<b.z+b.d/2+radius);}
export function move(s,vx,vz,dt,buildings,obstacles){if(s.mode!=='playing')return;const len=Math.hypot(vx,vz);if(len>1){vx/=len;vz/=len;}const n=Math.max(1,Math.ceil(dt*5.2/.2));for(let i=0;i<n;i++){const nx=s.player.x+vx*dt*5.2/n,nz=s.player.z+vz*dt*5.2/n;if(!isBlocked(nx,s.player.z,buildings,obstacles))s.player.x=nx;if(!isBlocked(s.player.x,nz,buildings,obstacles))s.player.z=nz;}}
